os:
  - linux
language: haskell
env:
  # - BRANCH="master"
  - BRANCH="devel"
install:
  - uname -a
  - curl https://nim-lang.org/choosenim/init.sh -sSf | sh
  - cabal install quickcheck
before_script:
  - export PATH=~/.nimble/bin:$PATH
script:
  - set -e
  - set -x
  - nim c example
  - make test
  - make quickcheck
notifications:
  email: false
